# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: Learning Portal
site_description: Choreo Learning Portal
site_author: WSO2
site_url: https://wso2.com/choreo/docs

# Repository
repo_name: wso2/docs-choreo-dev
repo_url: https://github.com/wso2/docs-choreo-dev/
edit_uri: https://github.com/wso2/docs-choreo-dev/edit/dev/en/docs/
dev_addr: localhost:8000

# Copyright
copyright: Â©2022 WSO2 LLC.

# Configuration
theme:
  name: material
  custom_dir: theme/material
  palette:
    primary: indigo
    accent: indigo
  logo: images/logo.svg
  favicon: images/favicon.png
  discord: images/discord-help-icon.svg
  choreo_logo: images/choreo-logo-icon.svg
  highlightjs: true
  feature:
    tabs: true
  font:
    text: 'Montserrat'
  language: 'en'
#Breaks build if there's a warning
strict: false
# Navigation
nav:
  - Home: index.md
  - Get Started:
      - What is Choreo?: get-started/what-is-choreo.md
      - Quick Start Guide: get-started/quick-start-guide.md
      - Tutorials: 
          - Create Your First REST API: get-started/tutorials/create-your-first-rest-api.md
          - Expose an Existing API via a REST API Proxy: get-started/tutorials/create-your-first-rest-api-proxy.md
          - Create Your First Webhook: get-started/tutorials/create-your-first-webhook.md
  - Create:
      - Components:
          - REST APIs: develop/components/rest-api.md
          - API Proxies: 
              - API Proxy: develop/components/api-proxies/api-proxy.md
              - Policies: develop/components/api-proxies/policies.md
          - Webhooks: develop/components/webhook.md
          - Scheduled Tasks: develop/components/scheduled-tasks.md
          - GraphQL APIs: develop/components/graphql-api.md
      - Manage Respository: 
          - Connect Your Own GitHub Repository: develop/manage-repository/connect-your-own-github-repository-to-choreo.md
      - Run and Test:
          - Forecast Performance Metrics: develop/run-and-test/forecast-performance-metrics.md
      - Advanced Topics:
          - Manage Connectors: develop/advanced-topics/manage-connectors.md
  - Deploy: 
      - Deploy Your Choreo Component: deploy/deploy-your-component.md
      - Deploy a Containerized Component: deploy/deploy-a-containerized-choreo-component.md
  - Test: 
      - OpenAPI Console: test/open-api-console.md
      - cURL: test/curl.md
  - Manage:
      - API Management: manage/api-management.md
      - Lifecycle: manage/lifecycle.md
  - Consume:
      - Developer Portal Overview: consume/developer-portal.md
      - Manage Application: consume/manage-application.md
      - Manage Subscription: consume/manage-subscription.md
      - Test APIs: consume/test-api.md
  - Marketplace: marketplace.md
  - Observe and Analyze:
      - Observe:
         - Observability Overview: observe-and-analyze/observe/observability-overview.md
         - Root Cause Analysis: observe-and-analyze/observe/root-cause-analysis.md
      - Analyze: 
          - View API Insights: observe-and-analyze/analyze/view-api-insights.md
          - Generate Custom Reports: observe-and-analyze/analyze/generate-custom-reports.md
          - Configure Alerts: observe-and-analyze/analyze/configure-alerts.md
          - Choreo Insights API: observe-and-analyze/analyze/choreo-insights-api.md
          - Programmatic Access to Choreo Insights API: observe-and-analyze/analyze/programmatic-access-choreo-insights-api.md
  - Alerts: alerts.md
  - DevOps: devops/devops-portal.md
  - Administer:
      - Connect to an External Identity Provider: administer/connect-to-an-external-identity-provider.md  
      - Configure a Custom Domain for APIs: administer/configure-a-custom-domain-for-apis.md
      - Configure Enterprise Login: administer/configure-enterprise-login.md
      - Developer Portal:
          - Configure a Custom Domain for Developer Portal: administer/customize-developer-portal-domain.md
          - Customize the Developer Portal: administer/customize-the-developer-portal.md
          - Configure Developer Portal Self-Sign-Up: administer/configure-developer-portal-self-sign-up.md
      - Organization: administer/organization.md
  - References:
     - Connect with Protected Third Party Applications: reference/connect-with-protected-third-party-applications.md
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
  - attr_list
  - markdown_include.include:
      base_path: docs
plugins:
  - search
  - markdownextradata: {}
  - redirects:
      redirect_maps:
          'tutorials/create-your-first-rest-api.md': 'https://wso2.com/choreo/docs/get-started/tutorials/create-your-first-rest-api/'
          'tutorials/connect-your-own-github-repository-to-choreo.md': 'https://wso2.com/choreo/docs/manage-repository/connect-your-own-github-repository-to-choreo/'
          'tutorials/construct-statements.md': 'https://wso2.com/choreo/docs/develop/explore-code-editor/construct-statements/'
          'tutorials/connect-your-existing-ballerina-project-to-choreo.md': 'https://wso2.com/choreo/docs/manage-repository/connect-your-existing-ballerina-project-to-choreo/'
          'tutorials/deploy-a-containerized-choreo-component.md': 'https://wso2.com/choreo/docs/deploy/deploy-a-containerized-choreo-component/'
          'tutorials/configure-automatic-deployment.md': 'https://wso2.com/choreo/docs/deploy/configure-automatic-deployment/'
          'tutorials/map-data.md': 'https://wso2.com/choreo/docs/develop/explore-code-editor/map-data/'
          'rest-api.md': 'https://wso2.com/choreo/docs/develop/components/rest-api/'
          'api-proxies.md': 'https://wso2.com/choreo/docs/develop/components/api-proxies/api-proxy/'
          'webhook.md': 'https://wso2.com/choreo/docs/develop/components/webhook/'
          'scheduled-tasks.md': 'https://wso2.com/choreo/docs/develop/components/scheduled-tasks/'
          'graphql-api.md': 'https://wso2.com/choreo/docs/develop/components/graphql-api/'
          'developer-portal/developer-portal.md': 'https://wso2.com/choreo/docs/consume/developer-portal/'
          'developer-portal/manage-application.md': 'https://wso2.com/choreo/docs/consume/manage-application/'
          'developer-portal/manage-subscription.md': 'https://wso2.com/choreo/docs/consume/manage-subscription/'
          'developer-portal/test-api.md': 'https://wso2.com/choreo/docs/consume/test-api/'
          'devops-portal.md': 'https://wso2.com/choreo/docs/devops/devops-portal/'
          'insights/view-api-insights.md': 'https://wso2.com/choreo/docs/observe-and-analyze/analyze/view-api-insights/'
          'insights/generate-custom-reports.md': 'https://wso2.com/choreo/docs/observe-and-analyze/analyze/generate-custom-reports/'
          'insights/configure-alerts.md': 'https://wso2.com/choreo/docs/observe-and-analyze/analyze/configure-alerts/'
          'insights/choreo-insights-api.md': 'https://wso2.com/choreo/docs/observe-and-analyze/analyze/choreo-insights-api/'
          'insights/programmatic-access-choreo-insights-api.md': 'https://wso2.com/choreo/docs/observe-and-analyze/analyze/programmatic-access-choreo-insights-api/'
          'administration/connect-to-an-external-identity-provider.md': 'https://wso2.com/choreo/docs/administration/connect-to-an-external-identity-provider/'
          'administration/customize-developer-portal-domain.md': 'https://wso2.com/choreo/docs/administration/customize-developer-portal-domain/'
          'administration/configure-a-custom-domain-for-apis.md': 'https://wso2.com/choreo/docs/administration/configure-a-custom-domain-for-apis/'
          'administration/customize-the-developer-portal.md': 'https://wso2.com/choreo/docs/administration/customize-the-developer-portal/'
          'administration/configure-enterprise-login.md': 'https://wso2.com/choreo/docs/administration/configure-enterprise-login/'
          'administration/configure-developer-portal-self-sign-up.md': 'https://wso2.com/choreo/docs/administration/configure-developer-portal-self-sign-up/'
          'observability/observability-overview.md': 'https://wso2.com/choreo/docs/observe-and-analyze/observe/observability-overview/'
          'observability/root-cause-analysis.md': 'https://wso2.com/choreo/docs/observe-and-analyze/observe/root-cause-analysis/'
          'references/performance-analysis.md': 'https://wso2.com/choreo/docs/develop/run-and-test/forecast-performance-metrics/'
          'references/alerting.md': 'https://wso2.com/choreo/docs/alerts/'
          'references/manage-connectors.md': 'https://wso2.com/choreo/docs/develop/advanced-topics/manage-connectors/'
          'references/handle-non-ballerina-files-in-choreo.md': 'https://wso2.com/choreo/docs/develop/explore-code-editor/handle-non-ballerina-files-in-choreo/'
          'references/define-configurable-variables.md': 'https://wso2.com/choreo/docs/develop/explore-code-editor/define-configurable-variables/'
          'references/connect-with-protected-third-party-applications.md': 'https://wso2.com/choreo/docs/references/connect-with-protected-third-party-applications/'
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
  - assets/css/prism.css
  - assets/lib/json-formatter/json-formatter.css
extra_javascript:
  - assets/lib/json-formatter/json-formatter.umd.js
  - assets/lib/highlightjs/highlight.min.js
  - assets/lib/prism/prism.js
  - assets/js/theme.js
  - assets/js/prism-ballerina.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 1.0.0
  #base_path: http://localhost:8000
