# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: ""
site_description: Choreo Learning Portal
site_author: WSO2
site_url: https://wso2.com/choreo/docs

# Repository
repo_name: wso2/docs-choreo-dev
repo_url: https://github.com/wso2/docs-choreo-dev/
edit_uri: https://github.com/wso2/docs-choreo-dev/edit/dev/en/docs/
dev_addr: localhost:8000

# Copyright
copyright: Â©2023 WSO2 LLC.

# Configuration
theme:
  name: material
  custom_dir: theme/material
  logo: assets/img/logo.png
  font:
    text: Montserrat
  favicon: assets/images/favicon.png
  features:    
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - content.action.view
  language: 'en'
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    logo: logo
#Breaks build if there's a warning
strict: false
# Navigation
nav:
  - Home: index.md
  - Introduction:
      - What is Choreo?: what-is-choreo.md
  - Quick Start Guides:
      - Build Your First Cloud Native Application with Choreo: quick-start-guides/build-your-first-cloud-native-application-with-choreo.md
      - Expose a Service as a Managed API with Choreo API Manager: quick-start-guides/expose-a-service-as-a-managed-api-with-choreo-api-manager.md
      - Build Your First Integration with Choreo iPaaS: quick-start-guides/build-your-first-integration-with-choreo-ipaas.md
  - Choreo Concepts:
      - Resource Hierarchy: choreo-concepts/resource-hierarchy.md
      - Organization: choreo-concepts/organization.md
      - Project: choreo-concepts/project.md
      - Component: choreo-concepts/component.md
      - Endpoint: choreo-concepts/endpoint.md
      - Data Planes: choreo-concepts/data-planes.md
      - Environments: choreo-concepts/environments.md
  - Develop Components:
      - Develop Components Using VS Code: develop-components/develop-components-using-vs-code.md
      - Develop Services:
          - REST API: develop-components/develop-services/develop-a-rest-api.md
      - Develop Integrations:
          - Develop an Integration with Integration Studio: develop-components/develop-integrations/develop-an-integration-with-integration-studio.md
          - Develop an Event-Triggered Integration: develop-components/develop-integrations/develop-an-event-triggered-integration.md
          - Develop a Scheduled Integration: develop-components/develop-integrations/develop-a-scheduled-integration.md
  - DevOps and CI/CD: 
      - Builds and Deployments: devops-and-ci-cd/builds-and-deployments.md
      - Manage Configurations and Secrets: devops-and-ci-cd/manage-configurations-and-secrets.md
      - View Runtime Details: devops-and-ci-cd/view-runtime-details.md
      - Configure Container Resources, Commands, and Arguments: devops-and-ci-cd/configure-container-resources-commands-and-arguments.md
      - Set Up Health Checks: devops-and-ci-cd/set-up-health-checks.md
      - Autoscale Component Replicas: devops-and-ci-cd/autoscale-component-replicas.md
      - Configure Storage: devops-and-ci-cd/configure-storage.md
      - Manage Environments: devops-and-ci-cd/manage-environments.md
  - Testing: 
      - Test REST Endpoints via the OpenAPI Console: testing/test-rest-endpoints-via-the-openapi-console.md
      - Test GraphQL Endpoints via the GraphQL Console: testing/test-graphql-endpoints-via-the-graphql-console.md
      - Test APIs with cURL: testing/test-apis-with-curl.md
      - Test APIs using Postman: testing/test-apis-using-postman.md
  - Consuming Services:
      - Manage Application: consuming-services/manage-application.md
      - Manage Subscription: consuming-services/manage-subscription.md
  - API Management:
      - Lifecycle Management: api-management/lifecycle-management.md
      - Documents: api-management/documents.md
      - API Rate Limiting: api-management/api-rate-limiting.md
  - Monitoring and Insights:
      - Observability Overview: monitoring-and-insights/observability-overview.md
      - View API Insights: monitoring-and-insights/view-api-insights.md
      - Generate Custom Reports: monitoring-and-insights/generate-custom-reports.md
      - Alerts:
          - Configure Alerts: monitoring-and-insights/alerts/configure-alerts.md
  - Administer:
      - Configure a Custom Domain for APIs: administer/configure-a-custom-domain-for-apis.md
      - Developer Portal:
          - Customize the Developer Portal: administer/customize-the-developer-portal.md
          - Configure Self-Sign-Up: administer/configure-self-sign-up.md
          - Customize the Developer Portal Domain: administer/customize-the-developer-portal-domain.md
# Extensions
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
  - attr_list
plugins:
  - search
  - glightbox
  - markdownextradata: {}
  - redirects:
      redirect_maps:
          'tutorials/create-your-first-rest-api.md': 'https://wso2.com/choreo/docs/get-started/tutorials/create-your-first-rest-api/'
          'tutorials/connect-your-own-github-repository-to-choreo.md': 'https://wso2.com/choreo/docs/manage-repository/connect-your-own-github-repository-to-choreo/'
          'tutorials/construct-statements.md': 'https://wso2.com/choreo/docs/develop/explore-code-editor/construct-statements/'
          'tutorials/connect-your-existing-ballerina-project-to-choreo.md': 'https://wso2.com/choreo/docs/manage-repository/connect-your-existing-ballerina-project-to-choreo/'
          'tutorials/configure-automatic-deployment.md': 'https://wso2.com/choreo/docs/deploy/configure-automatic-deployment/'
          'tutorials/map-data.md': 'https://wso2.com/choreo/docs/develop/explore-code-editor/map-data/'
          'rest-api.md': 'https://wso2.com/choreo/docs/develop/components/rest-api/'
          'api-proxies.md': 'https://wso2.com/choreo/docs/develop/components/api-proxy/'
          'api-proxies/api-proxy.md': 'https://wso2.com/choreo/docs/develop/components/api-proxy/'
          'webhook.md': 'https://wso2.com/choreo/docs/develop/components/webhook/'
          'scheduled-tasks.md': 'https://wso2.com/choreo/docs/develop/components/scheduled-trigger/'
          'manual-triggers.md': 'https://wso2.com/choreo/docs/develop/components/manual-trigger/'
          'graphql-api.md': 'https://wso2.com/choreo/docs/develop/components/graphql-api/'
          'developer-portal/developer-portal.md': 'https://wso2.com/choreo/docs/consume/developer-portal/'
          'developer-portal/manage-application.md': 'https://wso2.com/choreo/docs/consume/manage-application/'
          'developer-portal/manage-subscription.md': 'https://wso2.com/choreo/docs/consume/manage-subscription/'
          'developer-portal/test-api.md': 'https://wso2.com/choreo/docs/consume/test-api/'
          'insights/view-api-insights.md': 'https://wso2.com/choreo/docs/observe-and-analyze/analyze/view-api-insights/'
          'insights/generate-custom-reports.md': 'https://wso2.com/choreo/docs/observe-and-analyze/analyze/generate-custom-reports/'
          'insights/configure-alerts.md': 'https://wso2.com/choreo/docs/observe-and-analyze/analyze/configure-alerts/'
          'insights/choreo-insights-api.md': 'https://wso2.com/choreo/docs/observe-and-analyze/analyze/choreo-insights-api/'
          'insights/programmatic-access-choreo-insights-api.md': 'https://wso2.com/choreo/docs/observe-and-analyze/analyze/programmatic-access-choreo-insights-api/'
          'administration/connect-to-an-external-identity-provider.md' : 'https://wso2.com/choreo/docs/administer/connect-to-an-external-identity-provider/'
          'administration/customize-developer-portal-domain.md': 'https://wso2.com/choreo/docs/administer/customize-developer-portal-domain/'
          'administration/configure-a-custom-domain-for-apis.md': 'https://wso2.com/choreo/docs/administer/configure-a-custom-domain-for-apis/'
          'administration/customize-the-developer-portal.md': 'https://wso2.com/choreo/docs/administer/customize-the-developer-portal/'
          'administration/configure-enterprise-login.md': 'https://wso2.com/choreo/docs/administer/configure-enterprise-login/'
          'administration/configure-developer-portal-self-sign-up.md': 'https://wso2.com/choreo/docs/administer/configure-developer-portal-self-sign-up/'
          'observability/observability-overview.md': 'https://wso2.com/choreo/docs/observe-and-analyze/observe/observability-overview/'
          'observability/root-cause-analysis.md': 'https://wso2.com/choreo/docs/observe-and-analyze/observe/root-cause-analysis/'
          'references/performance-analysis.md': 'https://wso2.com/choreo/docs/develop/run-and-test/forecast-performance-metrics/'
          'references/alerting.md': 'https://wso2.com/choreo/docs/alerts/'
          'references/manage-connectors.md': 'https://wso2.com/choreo/docs/develop/advanced-topics/manage-connectors/'
          'references/handle-non-ballerina-files-in-choreo.md': 'https://wso2.com/choreo/docs/develop/explore-code-editor/handle-non-ballerina-files-in-choreo/'
          'references/define-configurable-variables.md': 'https://wso2.com/choreo/docs/develop/explore-code-editor/define-configurable-variables/'
          'references/connect-with-protected-third-party-applications.md': 'https://wso2.com/choreo/docs/references/connect-with-protected-third-party-applications/'
          'develop/components/api-proxies/policies.md': 'https://wso2.com/choreo/docs/develop/api-policies/policies/'
          'get-started/what-is-choreo.md': 'https://wso2.com/choreo/docs/what-is-choreo/'
          'get-started/quick-start-guide.md': 'https://wso2.com/choreo/docs/quick-start-guides/build-your-first-cloud-native-application-with-choreo/'
          'get-started/tutorials/create-your-first-rest-api.md': 'https://wso2.com/choreo/docs/quick-start-guides/build-your-first-cloud-native-application-with-choreo/'
          'get-started/tutorials/create-your-first-rest-api-proxy.md': 'https://wso2.com/choreo/docs'
          'get-started/tutorials/create-your-first-webhook.md': 'https://wso2.com/choreo/docs'
          'get-started/tutorials/create-your-first-integration-as-an-api.md': 'https://wso2.com/choreo/docs/quick-start-guides/build-your-first-integration-with-choreo-ipaas/'
          'get-started/tutorials/create-your-first-event-triggered-integration.md': 'https://wso2.com/choreo/docs/develop-components/develop-integrations/develop-an-event-triggered-integration/'
          'get-started/tutorials/secure-an-api-with-role-based-access-control.md': 'https://wso2.com/choreo/docs'
          'get-started/tutorials/create-your-first-containerized-service-component.md': 'https://wso2.com/choreo/docs'
          'get-started/tutorials/deploy-a-containerized-application-as-an-event-triggered-integration.md': 'https://wso2.com/choreo/docs'
          'develop/components/rest-api.md': 'https://wso2.com/choreo/docs'
          'develop/components/api-proxy.md': 'https://wso2.com/choreo/docs'
          'develop/components/webhook.md': 'https://wso2.com/choreo/docs'
          'develop/components/scheduled-trigger.md': 'https://wso2.com/choreo/docs'
          'develop/components/manual-trigger.md': 'https://wso2.com/choreo/docs'
          'develop/components/graphql-api.md': 'https://wso2.com/choreo/docs'
          'develop/components/service.md': 'https://wso2.com/choreo/docs'
          'develop/manage-repository/connect-your-own-github-repository-to-choreo.md': 'https://wso2.com/choreo/docs'
          'develop/run-and-test/forecast-performance-metrics.md': 'https://wso2.com/choreo/docs'
          'develop/api-policies/policies.md': 'https://wso2.com/choreo/docs'
          'develop/api-policies/create-a-policy.md': 'https://wso2.com/choreo/docs'
          'develop/api-policies/attach-policies.md': 'https://wso2.com/choreo/docs'
          'deploy/deploy-a-ballerina-application.md': 'https://wso2.com/choreo/docs'
          'deploy/deploy-a-containerized-application.md': 'https://wso2.com/choreo/docs'
          'deploy/devops/runtime.md': 'https://wso2.com/choreo/docs/devops-and-ci-cd/view-runtime-details/'
          'deploy/devops/containers.md': 'https://wso2.com/choreo/docs/devops-and-ci-cd/configure-container-resources-commands-and-arguments/'
          'deploy/devops/configs-and-secrets.md': 'https://wso2.com/choreo/docs/devops-and-ci-cd/manage-configurations-and-secrets/'
          'deploy/devops/health-checks.md': 'https://wso2.com/choreo/docs/devops-and-ci-cd/set-up-health-checks/'
          'deploy/devops/scaling.md': 'https://wso2.com/choreo/docs/devops-and-ci-cd/autoscale-component-replicas/'
          'deploy/devops/storage.md': 'https://wso2.com/choreo/docs/devops-and-ci-cd/configure-storage/'
          'test/invoke-apis-via-console.md': 'https://wso2.com/choreo/docs/testing/test-rest-endpoints-via-the-openapi-console/'
          'test/open-api-console.md': 'https://wso2.com/choreo/docs/testing/test-rest-endpoints-via-the-openapi-console/'
          'test/curl.md': 'https://wso2.com/choreo/docs/devops-and-ci-cd/configure-storage/'
          'test/graphql-console.md': 'https://wso2.com/choreo/docs/testing/test-graphql-endpoints-via-the-graphql-console/'
          'manage/api-management.md': 'https://wso2.com/choreo/docs/api-management/lifecycle-management/'
          'manage/lifecycle.md': 'https://wso2.com/choreo/docs/api-management/lifecycle-management/'
          'manage/api-security/pass-end-user-attributes-to-the-backend.md': 'https://wso2.com/choreo/docs/api-management/api-rate-limiting/'
          'manage/api-rate-limiting.md': 'https://wso2.com/choreo/docs'
          'consume/developer-portal.md': 'https://wso2.com/choreo/docs'
          'consume/manage-application.md': 'https://wso2.com/choreo/docs/consuming-services/manage-application/'
          'consume/manage-subscription.md': 'https://wso2.com/choreo/docs/consuming-services/manage-subscription/'
          'consume/test-api.md': 'https://wso2.com/choreo/docs/testing/test-rest-endpoints-via-the-openapi-console/'
          'marketplace.md': 'https://wso2.com/choreo/docs'
          'observe-and-analyze/observe/observability-overview.md': 'https://wso2.com/choreo/docs/monitoring-and-insights/observability-overview/'
          'observe-and-analyze/observe/root-cause-analysis.md': 'https://wso2.com/choreo/docs'
          'observe-and-analyze/analyze/view-api-insights.md': 'https://wso2.com/choreo/docs/monitoring-and-insights/view-api-insights/'
          'observe-and-analyze/analyze/generate-custom-reports.md': 'https://wso2.com/choreo/docs/monitoring-and-insights/generate-custom-reports/'
          'observe-and-analyze/analyze/configure-alerts.md': 'https://wso2.com/choreo/docs/alerts/configure-alerts/'
          'observe-and-analyze/analyze/choreo-insights-api.md': 'https://wso2.com/choreo/docs'
          'observe-and-analyze/analyze/programmatic-access-choreo-insights-api.md': 'https://wso2.com/choreo/docs'
          'observe-and-analyze/analyze/dora-metrics/configure-cio-dashboard.md': 'https://wso2.com/choreo/docs'
          'observe-and-analyze/analyze/dora-metrics/view-dora-metrics.md': 'https://wso2.com/choreo/docs'
          'alerts.md': 'https://wso2.com/choreo/docs/alerts/configure-alerts/'
          'ipaas/get-started-with-choreo-ipaas.md': 'https://wso2.com/choreo/docs/quick-start-guides/build-your-first-integration-with-choreo-ipaas/'
          'ipaas/ballerina/develop-integrations-with-ballerina.md': 'https://wso2.com/choreo/docs/quick-start-guides/build-your-first-integration-with-choreo-ipaas/'
          'ipaas/ballerina/create-your-first-event-triggered-integration.md': 'https://wso2.com/choreo/docs/develop-integrations/develop-an-event-triggered-integration/'
          'ipaas/micro-integrator/develop-integrations-with-integration-studio.md': 'https://wso2.com/choreo/docs/develop-integrations/develop-an-integration-with-integration-studio/'
          'ipaas/micro-integrator/create-your-first-integration.md': 'https://wso2.com/choreo/docs/quick-start-guides/build-your-first-integration-with-choreo-ipaas/'
          'administer/connect-to-an-external-identity-provider.md': 'https://wso2.com/choreo/docs'
          'administer/configure-a-custom-domain-for-apis.md': 'https://wso2.com/choreo/docs/administer/configure-a-custom-domain-for-apis/'
          'administer/configure-enterprise-login.md': 'https://wso2.com/choreo/docs'
          'administer/customize-developer-portal-domain.md': 'https://wso2.com/choreo/docs//administer/customize-the-developer-portal-domain/'
          'administer/customize-the-developer-portal.md': 'https://wso2.com/choreo/docs/administer/customize-the-developer-portal/'
          'administer/configure-developer-portal-self-sign-up.md': 'https://wso2.com/choreo/docs/administer/configure-self-sign-up/'
          'administer/organization.md': 'https://wso2.com/choreo/docs/choreo-concepts/organization/'
          'reference/connect-with-protected-third-party-applications.md': 'https://wso2.com/choreo/docs'	
extra_css:
  # - assets/lib/highlightjs/default.min.css
  # - assets/css/theme.css
  # - assets/css/prism.css
  # - assets/lib/json-formatter/json-formatter.css
  
  - assets/lib/highlightjs/styles/vs.min.css
  - assets/css/blue-palette-alt2.css
  - assets/css/choreotheme.css
  - assets/lib/json-formatter/json-formatter.css
  - assets/css/config-catalog.css
  - assets/lib/fontawesome-free-6.3.0-web/css/all.min.css  
extra_javascript:
  - assets/lib/json-formatter/json-formatter.umd.js
  - assets/lib/highlightjs/highlight.min.js
 # - assets/js/theme.js
  #- assets/js/prism-ballerina.js
  - assets/js/choreotheme.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wso2
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wso2
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wso2
#site_version: 1.0.0
#base_path: http://localhost:8000

